// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionSystem.Data;

#nullable disable

namespace ProductionSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ProductionSystem.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimalStock")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimalStock = 100m,
                            Name = "Сталь листовая",
                            Quantity = 500m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 2,
                            MinimalStock = 150m,
                            Name = "Алюминий",
                            Quantity = 80m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 3,
                            MinimalStock = 500m,
                            Name = "Болты М8",
                            Quantity = 2000m,
                            UnitOfMeasure = "шт"
                        },
                        new
                        {
                            Id = 4,
                            MinimalStock = 50m,
                            Name = "Масло машинное",
                            Quantity = 30m,
                            UnitOfMeasure = "литр"
                        },
                        new
                        {
                            Id = 5,
                            MinimalStock = 100m,
                            Name = "Пластик АБС",
                            Quantity = 300m,
                            UnitOfMeasure = "кг"
                        });
                });

            modelBuilder.Entity("ProductionSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimalStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionTimePerUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Насосы",
                            Description = "Корпус центробежного насоса",
                            MinimalStock = 10,
                            Name = "Корпус насоса",
                            ProductionTimePerUnit = 45
                        },
                        new
                        {
                            Id = 2,
                            Category = "Редукторы",
                            Description = "Крышка цилиндрического редуктора",
                            MinimalStock = 5,
                            Name = "Крышка редуктора",
                            ProductionTimePerUnit = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Конструкции",
                            Description = "Опорный кронштейн для оборудования",
                            MinimalStock = 20,
                            Name = "Кронштейн опорный",
                            ProductionTimePerUnit = 15
                        });
                });

            modelBuilder.Entity("ProductionSystem.Models.ProductMaterial", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            MaterialId = 1,
                            QuantityNeeded = 5.5m
                        },
                        new
                        {
                            ProductId = 1,
                            MaterialId = 3,
                            QuantityNeeded = 8m
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 2,
                            QuantityNeeded = 3.2m
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 3,
                            QuantityNeeded = 12m
                        },
                        new
                        {
                            ProductId = 3,
                            MaterialId = 1,
                            QuantityNeeded = 2.0m
                        },
                        new
                        {
                            ProductId = 3,
                            MaterialId = 3,
                            QuantityNeeded = 4m
                        });
                });

            modelBuilder.Entity("ProductionSystem.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentWorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EfficiencyFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWorkOrderId");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfficiencyFactor = 1f,
                            Name = "Линия А — Механообработка",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            EfficiencyFactor = 1.2f,
                            Name = "Линия Б — Сборка",
                            Status = "Stopped"
                        },
                        new
                        {
                            Id = 3,
                            EfficiencyFactor = 0.8f,
                            Name = "Линия В — Покраска",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ProductionSystem.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedEndDate = new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            ProductionLineId = 1,
                            Progress = 0,
                            Quantity = 10,
                            StartDate = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            EstimatedEndDate = new DateTime(2025, 1, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Progress = 0,
                            Quantity = 5,
                            StartDate = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ProductionSystem.Models.ProductMaterial", b =>
                {
                    b.HasOne("ProductionSystem.Models.Material", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Models.Product", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionSystem.Models.ProductionLine", b =>
                {
                    b.HasOne("ProductionSystem.Models.WorkOrder", "CurrentWorkOrder")
                        .WithMany()
                        .HasForeignKey("CurrentWorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentWorkOrder");
                });

            modelBuilder.Entity("ProductionSystem.Models.WorkOrder", b =>
                {
                    b.HasOne("ProductionSystem.Models.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Models.ProductionLine", "ProductionLine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionSystem.Models.Material", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("ProductionSystem.Models.Product", b =>
                {
                    b.Navigation("ProductMaterials");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ProductionSystem.Models.ProductionLine", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
